### ISSUE TITLE
Any solution to this problem?

### ISSUE THREAD

**Issue by fulviocanducci** [apalfrey/select2-bootstrap-5-theme#59] opened 2022-01-16 20:41 UTC
Does not work "select2--small"

https://github.com/apalfrey/select2-bootstrap-5-theme/issues/57

???

**Comment by fulviocanducci** [comment] 2022-01-16 21:00
A example: https://jsfiddle.net/fulviocanducci/Lm2xa3zo/

The search box stays with the css lg, even passing the "select2--small" setting

**Comment by apalfrey** [comment] 2022-02-22 17:47
There's a solution pending release, however as this is a duplicate of #57, I'll have to close this issue as such

**Closed by apalfrey** 2022-02-22 17:47 UTC
